name: C++ Build and Test on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use GitHub's pre-configured Windows environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Install CMake (if not already installed)
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    # Step 3: Create the build directory and build the project with CMake
    - name: Build Project with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019"  # Change to "Visual Studio 17 2022" for newer versions
        cmake --build . --config Release

    # Step 4: Run tests with CTest
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    # Step 5: Clean up build files (optional)
    - name: Clean up
      run: |
        Remove-Item -Recurse -Force build
