name: C++ Build with MinGW on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Install MinGW via Chocolatey
    - name: Install MinGW
      run: |
        choco install mingw --installargs 'ADD_MINGW_TO_PATH=System'

    # Step 3: Build the project with MinGW using CMake
    - name: Build Project with MinGW
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"  # Use MinGW Makefiles generator
        cmake --build . --config Release

    # Step 4: Upload the .exe as Artifact
    - name: Upload .exe as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: build/Release/my-app.exe  # Adjust path based on your project's output

    # Optional: Run tests (if applicable)
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    # Clean up build files (optional)
    - name: Clean up
      run: |
        Remove-Item -Recurse -Force build
